# Connections
max_connections = 500
superuser_reserved_connections = 10

# Example for 8G memory
shared_buffers = 2GB
work_mem = 8MB
effective_cache_size = 6GB
maintenance_work_mem = 512MB

# Read/Write
wal_buffers = 16MB
checkpoint_completion_target = 0.9

# Example for 4 processor
max_worker_processes = 4
max_parallel_workers = 4
max_parallel_workers_per_gather = 2