services:
  postgres:
    build:
      context: .
      dockerfile: DockerfilePSQL18
    container_name: pg_server18
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./custom-postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pg_data:
    driver: local
