services:
  postgres:
    build: .
    container_name: pg_server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./custom-postgres.conf:/etc/postgresql/postgresql.conf
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pg_data:
    driver: local