stages:
  - build
  - deploy

##Global variables
variables:
  IMAGE_NAME_: $CI_REGISTRY_IMAGE
  SRC_DIRECTORY_: './Eshop'

## Build image part
.build_docker_image:
  variables:
    IMAGE_TAG_: toorball_eshop
    DOCKERFILE_NAME_: DockerfileEshop
    IMAGE_NAME_PATTERN:
    EXPOSE_PORT_PATTERN:
    EXPOSE_PORT:
    BRANCH:
    GIT_TAG:
    ENV_FILE_:
    ENV_FILE_NAME_: .env
    DOTNET: false
  stage: build
  rules:
    - if: '( ( $CI_COMMIT_TAG =~ $GIT_TAG && $GIT_TAG != "" ) || ( $BRANCH == $CI_COMMIT_BRANCH && $BRANCH != "" ) )'
  script:
    - |
      if [ "$CI_COMMIT_TAG" != "" ]; then
        export IMAGE_TAG_=$CI_COMMIT_TAG
      fi
      if [ -z "$EXPOSE_PORT" ]; then
        echo "EXPOSE_PORT_ variable shouldn't be empty!"
        exit 1
      fi
    - cd $SRC_DIRECTORY_
    # - echo "Force Dockerfile to user runflare mirrors"
    # - sed -i 's|RUN npm install|RUN npm install --registry="https://package-mirror.liara.ir/repository/npm/"|' Dockerfile
    # - sed -i 's|RUN pip install|RUN pip install -i https://mirror-pypi.runflare.com/simple|' Dockerfile
    - echo "Copy $ENV_FILE_NAME_ file"
    - |
      if [ -f "$ENV_FILE_" ]; then
        cp $ENV_FILE_ $ENV_FILE_NAME_
      fi

    # Microsoft bypass part...
    - |
      if [ "$DOTNET" = "true" ]; then
        echo "Only for microsoft images..."
        if ! docker image inspect "mcr.microsoft.com/dotnet/sdk:9.0" > /dev/null 2>&1; then
          wget https://codekit.s3.ir-thr-at1.arvanstorage.ir/dotnetsdk9.0.tar -O dotnetsdk9.0.tar
          docker load -i dotnetsdk9.0.tar
          rm dotnetsdk9.0.tar
        fi
        if ! docker image inspect "mcr.microsoft.com/dotnet/aspnet:9.0" > /dev/null 2>&1; then
          wget https://codekit.s3.ir-thr-at1.arvanstorage.ir/dotnetaspnet9.0.tar -O dotnetaspnet9.0.tar
          docker load -i dotnetaspnet9.0.tar
          rm dotnetaspnet9.0.tar
        fi
      else
        echo "Skipping Microsoft images download (DOTNET is not true)"
      fi

    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

    - echo "Building Docker image ${IMAGE_NAME_}:${IMAGE_TAG_}... from ${DOCKERFILE_NAME_} ${SRC_DIRECTORY_}"
    - docker build  --network=host -t $IMAGE_NAME_:$IMAGE_TAG_ -f $DOCKERFILE_NAME_ .
    - docker push $IMAGE_NAME_:$IMAGE_TAG_

    ## 2. Image file sharing mode
    # - echo "Saving Docker image to file $CI_PROJECT_NAME.tar"
    # - docker save $IMAGE_NAME_:$IMAGE_TAG_ -o $IMAGE_NAME_.tar

    # - scp -P $SSH_PORT_ -o IdentityFile=~/.ssh/id_edtemp $IMAGE_NAME_.tar $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.

    ## Make docker-compose ready and export to server
    - echo "Make docker-compose ready and export to server"
    - sed -i "s|${IMAGE_NAME_PATTERN}|${IMAGE_NAME_}:${IMAGE_TAG_}|" ./docker-compose.yml
    - sed -i "s|${EXPOSE_PORT_PATTERN}|${EXPOSE_PORT}|g" ./docker-compose.yml
  artifacts:
    paths:
      - $SRC_DIRECTORY_/docker-compose.yml
      - $SRC_DIRECTORY_/$ENV_FILE_NAME_
    expire_in: 1 hours
##Now use image builder model



## Deploy part
.deploy_docker_image:
  variables:
    SSH_PRIVATE_KEY_:
    SSH_PORT_:
    SERVER_IP_:
    SERVER_USER_:
    SERVER_PATH_:
    ENV_FILE_NAME_: .env
    GIT_TAG:
    BRANCH:
  stage: deploy
  rules:
    - if: '( ( $CI_COMMIT_TAG =~ $GIT_TAG && $GIT_TAG != "" ) || ( $BRANCH == $CI_COMMIT_BRANCH && $BRANCH != "" ) )'
  script:
    - cd $SRC_DIRECTORY_
    # - echo "Copy .env file"
    # - cp $ENV_FILE_ .env
    ## Get ready to send image file to server
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_" > ~/.ssh/id_edtemp
    - chmod 600 ~/.ssh/id_edtemp
    - ssh-keyscan -p $SSH_PORT_ $SERVER_IP_ >> ~/.ssh/known_hosts

    - |
      ssh -p $SSH_PORT_ -o StrictHostKeyChecking=no \
          -o IdentityFile=~/.ssh/id_edtemp \
          $SERVER_USER_@$SERVER_IP_ << EOF
            mkdir -p ${SERVER_PATH_}
      EOF

    - |
      if [ -f "./docker-compose.yml" ]; then
        scp -P $SSH_PORT_ -o IdentityFile=~/.ssh/id_edtemp ./docker-compose.yml $SERVER_USER_@$SERVER_IP_:$SERVER_PATH_/new.docker-compose.yml
      fi
    - |
      if [ -f "./$ENV_FILE_NAME_" ] ; then
        scp -P $SSH_PORT_ -o IdentityFile=~/.ssh/id_edtemp ./$ENV_FILE_NAME_ $SERVER_USER_@$SERVER_IP_:$SERVER_PATH_/$ENV_FILE_NAME_
      fi
    ## 1. Now push the Image to self registry
    - |
      ssh -p $SSH_PORT_ -o StrictHostKeyChecking=no \
          -o IdentityFile=~/.ssh/id_edtemp \
          $SERVER_USER_@$SERVER_IP_ << EOF
            echo "Move to ${SERVER_PATH_}"
            cd ${SERVER_PATH_}
            echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
            docker compose -f new.docker-compose.yml pull
            docker compose down || true
            mv new.docker-compose.yml docker-compose.yml
            docker compose up -d
      EOF
    ## 2. Image file sharing mode
    # - scp -P $SSH_PORT_ -o IdentityFile=~/.ssh/id_edtemp $IMAGE_NAME_.tar $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.
    # - rm $IMAGE_NAME_.tar

    # - |
    #   ssh -p $SSH_PORT_ -o StrictHostKeyChecking=no \
    #       -o IdentityFile=~/.ssh/id_edtemp \
    #       $SERVER_USER_@$SERVER_IP_ << EOF
    #         echo "Move to ${SERVER_PATH_}"
    #         cd ${SERVER_PATH_}
    #         echo "Load image ${IMAGE_NAME_}.tar"
    #         docker load -i ./${IMAGE_NAME_}.tar
    #         docker compose down
    #         docker compose up -d
    #   EOF




## Examples

# build_docker:
#   extends: .build_docker_image
#   variables:
    # IMAGE_TAG_: toorball_eshop # Or use GIT_TAG and skip it
    # DOCKERFILE_NAME_: Dockerfile
    # IMAGE_NAME_PATTERN: # From docker-compose.yml file
    # EXPOSE_PORT_PATTERN: # From docker-compose.yml file
    # EXPOSE_PORT: # From gitlab variables
    # BRANCH: # Branch name
    # GIT_TAG: /^karmaye-/ # tag patter or leave it empty
    # ENV_FILE_: # env file in variables
    # DOTNET: false # make it true if you are deploying .net projects


# deploy_docker:
#   extends: .deploy_docker_image
#   needs: 
#     - build_docker # Name the earlier action
#   variables:
#     SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY_CODEKIT
#     SSH_PORT_: $SSH_PORT_CODEKIT
#     SERVER_IP_: $SERVER_IP_CODEKIT
#     SERVER_USER_: $SERVER_USER_CODEKIT  
#     SERVER_PATH_: $SERVER_PATH_TOPATR # like ./shop
#     BRANCH: topatr
