stages:
  - build

variables:
  # IMAGE_NAME_: $IMAGE_NAME
  # IMAGE_TAG_: latest
  # IMAGE_FILE_: $IMAGE_NAME_.tar
  SERVER_USER_: $SERVER_USER
  SERVER_IP_: $SERVER_IP
  SERVER_PATH_: $SERVER_PATH
  PM2_NAME_: $PM2_NAME
  NPM_BIN_PATH_: /home/ubuntu/.nvm/versions/node/v20.20.1/bin/
  SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY
  SRC_DIRECTORY_: '.'
  # lOCAL_PORT_: $lOCAL_PORT
  # ENV_FILE_: $ENV_FILE

###########################
#       BUILD Docker
###########################
build_on_server:
  tags:
    - shell
  stage: build
  only:
      - master
  script:
    # - echo "Force Dockerfile to user runflare mirrors"
    # - sed -i 's|RUN npm install|RUN npm install --registry="https://mirror-npm.runflare.com"|' Dockerfile
    # - sed -i 's|RUN pip install|RUN pip install -i https://mirror-pypi.runflare.com/simple|' Dockerfile
    # - echo "Copy .env file"
    # - cp $ENV_FILE_ .env
    # - echo "Building Docker image ${IMAGE_NAME_}:${IMAGE_TAG_}..."
    # - docker build -t $IMAGE_NAME_:$IMAGE_TAG_ .
    # - echo "Saving Docker image to file $IMAGE_FILE_"
    # - docker save $IMAGE_NAME_:$IMAGE_TAG_ -o $IMAGE_FILE_

    ## Get ready to send image file to server
    - 'mkdir -p ~/.ssh'
    - 'echo "$SSH_PRIVATE_KEY_" > ~/.ssh/id_edtemp'
    - 'chmod 600 ~/.ssh/id_edtemp'
    - 'ssh-keyscan $SERVER_IP_ >> ~/.ssh/known_hosts'

    # - scp -o IdentityFile=~/.ssh/id_edtemp $IMAGE_FILE_ $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.
    # - rm $IMAGE_FILE_

    ## Make docker-compose ready and export to servre
    # - echo "Make docker-compose ready and export to servre"
    # - sed -i "s|image:.*|image:\ ${IMAGE_NAME_}|" $SRC_DIRECTORY_/docker-compose.yml
    # - sed -i "s|\$EXPOSE_PORT|${lOCAL_PORT_}|g" $SRC_DIRECTORY_/docker-compose.yml

    # - scp -o IdentityFile=~/.ssh/id_edtemp $SRC_DIRECTORY_/docker-compose.yml $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.

    ## Restart the docker compose file
    - |
      ssh -o StrictHostKeyChecking=no \
          -o IdentityFile=~/.ssh/id_edtemp \
          $SERVER_USER_@$SERVER_IP_ << EOF
            set -euo pipefail
            echo "Move to ${SERVER_PATH_}"
            mkdir -p ${SERVER_PATH_}
            rsync -rt ${SERVER_PATH_} /tmp${SERVER_PATH_}
            cd /tmp${SERVER_PATH_}
            git stash --include-untracked
            git pull
            export PATH=$PATH:$NPM_BIN_PATH_
            npm i
            npm run build
            echo ============================
            echo "===    Source is OK.   ==="
            echo ============================
            cd ${SERVER_PATH_}
            git stash --include-untracked
            git pull
            npm i
            npm run build
            pm2 restart $PM2_NAME_
      EOF
#   artifacts:
#     paths:
#       - $IMAGE_FILE_
#     expire_in: 2 hours
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
