stages:
  - build

variables:
  IMAGE_NAME_: $IMAGE_NAME
  IMAGE_TAG_: latest
  SERVER_USER_: $SERVER_USER
  SERVER_IP_: $SERVER_IP
  SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY
  SRC_DIRECTORY_: '.'
  SERVER_PATH_: $SERVER_PATH
  lOCAL_PORT_: $lOCAL_PORT
  ENV_FILE_: $ENV_FILE

###########################
#       BUILD Docker
###########################
build_docker_image:
  tags:
    - shell
  stage: build
  only:
      - main
  script:
    - echo "Force Dockerfile to user runflare mirrors"
    # - sed -i 's|RUN npm install|RUN npm install --registry="https://package-mirror.liara.ir/repository/npm/"|' Dockerfile
    # - sed -i 's|RUN pip install|RUN pip install -i https://mirror-pypi.runflare.com/simple|' Dockerfile
    - echo "Copy .env file"
    - cp $ENV_FILE_ .env

    ## Microsoft bypass part...
    # - echo "Only for microsoft images..."
    # - |
    #   if ! docker image inspect "mcr.microsoft.com/dotnet/sdk:9.0" > /dev/null 2>&1; then
    #     wget https://codekit.s3.ir-thr-at1.arvanstorage.ir/dotnetsdk9.0.tar -O dotnetsdk9.0.tar
    #     docker load -i dotnetsdk9.0.tar
    #   fi
    # - |
    #   if ! docker image inspect "mcr.microsoft.com/dotnet/aspnet:9.0" > /dev/null 2>&1; then
    #     wget https://codekit.s3.ir-thr-at1.arvanstorage.ir/dotnetaspnet9.0.tar -O dotnetaspnet9.0.tar
    #     docker load -i dotnetaspnet9.0.tar
    #   fi
    ## Microsoft bypass done

    - echo "Building Docker image ${IMAGE_NAME_}:${IMAGE_TAG_}..."
    - docker build -t $IMAGE_NAME_:$IMAGE_TAG_ .
    - echo "Saving Docker image to file $IMAGE_NAME_.tar"
    - docker save $IMAGE_NAME_:$IMAGE_TAG_ -o $IMAGE_NAME_.tar

    ## Get ready to send image file to server
    - 'mkdir -p ~/.ssh'
    - 'echo "$SSH_PRIVATE_KEY_" > ~/.ssh/id_edtemp'
    - 'chmod 600 ~/.ssh/id_edtemp'
    - 'ssh-keyscan $SERVER_IP_ >> ~/.ssh/known_hosts'

    - scp -o IdentityFile=~/.ssh/id_edtemp $IMAGE_NAME_.tar $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.
    - rm $IMAGE_NAME_.tar

    ## Make docker-compose ready and export to servre
    - echo "Make docker-compose ready and export to servre"
    - sed -i "s|image:.*|image:\ ${IMAGE_NAME_}|" $SRC_DIRECTORY_/docker-compose.yml
    - sed -i "s|\$EXPOSE_PORT|${lOCAL_PORT_}|g" $SRC_DIRECTORY_/docker-compose.yml

    - scp -o IdentityFile=~/.ssh/id_edtemp $SRC_DIRECTORY_/docker-compose.yml $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.
    - scp -o IdentityFile=~/.ssh/id_edtemp $SRC_DIRECTORY_/.env $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.

    ## Restart the docker compose file
    - |
      ssh -o StrictHostKeyChecking=no \
          -o IdentityFile=~/.ssh/id_edtemp \
          $SERVER_USER_@$SERVER_IP_ << EOF
            echo "Move to ${SERVER_PATH_}"
            cd ${SERVER_PATH_}
            echo "Load image ${IMAGE_NAME_}.tar"
            docker load -i ./${IMAGE_NAME_}.tar
            docker compose down
            docker compose up -d
      EOF
#   artifacts:
#     paths:
#       - $IMAGE_NAME_.tar
#     expire_in: 2 hours
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
