stages:
  - build
  - deploy

variables:
  IMAGE_NAME_: $IMAGE_NAME
  IMAGE_TAG_: latest
  IMAGE_FILE_: $IMAGE_FILE
  SERVER_USER_: $SERVER_USER
  SERVER_IP_: $SERVER_IP
  SERVER_PATH_: $SERVER_PATH
  SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY

###########################
#       BUILD Docker
###########################
build_docker_image:
  tags:
    - shell
  stage: build
  only:
      - main
  script:
    - echo "Force Dockerfile to user runflare mirrors"
    - sed -i 's|^RUN npm install|RUN npm install --registry="https://mirror-npm.runflare.com"|' Dockerfile
    - sed -i 's|^RUN pip install|RUN pip install -i https://mirror-pypi.runflare.com/simple|' Dockerfile
    - echo "Building Docker image ${IMAGE_NAME_}:${IMAGE_TAG_}..."
    - docker build -t $IMAGE_NAME_:$IMAGE_TAG_ .
    - echo "Saving Docker image to file $IMAGE_FILE_"
    - docker save $IMAGE_NAME_:$IMAGE_TAG_ -o $IMAGE_FILE_

    ## Get ready to send image file to server
    - 'mkdir -p ~/.ssh'
    - 'echo "$SSH_PRIVATE_KEY_" > ~/.ssh/id_edtemp'
    - 'chmod 600 ~/.ssh/id_edtemp'
    - 'ssh-keyscan $SERVER_IP_ >> ~/.ssh/known_hosts'

    - scp -o IdentityFile=~/.ssh/id_edtemp $IMAGE_FILE_ $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.
    - rm $IMAGE_FILE_
#   artifacts:
#     paths:
#       - $IMAGE_FILE_
#     expire_in: 2 hours
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'

# ##########################
#        DEPLOY
# ##########################
deploy_image_file:
  stage: deploy
  tags:
    - shell
#   before_script:
    # - sed -i 's/archive.ubuntu.com/mirror.arvancloud.ir/g' /etc/apt/sources.list
    # - apt-get update -qq && apt-get install -y -qq rsync openssh-client
    # - eval $(ssh-agent -s)
    # - echo "$SSH_PRIVATE_KEY_" | tr -d '\r' | ssh-add -
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    # - ssh-keyscan $SERVER_IP_ >> ~/.ssh/known_hosts
    # - chmod 644 ~/.ssh/known_hosts
  script:
    - 'mkdir -p ~/.ssh'
    - 'echo "$SSH_PRIVATE_KEY_" > ~/.ssh/id_edtemp'
    - 'chmod 600 ~/.ssh/id_edtemp'
    - 'ssh-keyscan $SERVER_IP_ >> ~/.ssh/known_hosts'
    - scp -o IdentityFile=~/.ssh/id_edtemp hi.txt $SERVER_USER_@$SERVER_IP_:~/$SERVER_PATH_/.
#   needs:
#     - build_docker_image
  only:
      - main2
  when: on_success
