concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlabce-sepehrino"
  url = "https://git.ngtartanak.co.ir/"
  token = "glrt-F_uX8-jQ0O20sfqefl"
  executor = "docker"
  [runners.cache]
    Path = "/home/gitlab-runner/cache"
    MaxUploadedArchiveSize = 0  
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = false
    disable_entrypoint_overwrite = true
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/gitlab-runner/cache:/cache"]
    pull_policy = ["if-not-present"]
    shm_size = 0
    network_mtu = 0
    cpus = "2"
    memory = "4g"
    memory_reservation = "20g"
    memory_swap = "4g"


[[runners]]
  name = "mhelli"
  url = "https://git.ngtartanak.co.ir/"
  token = "glrt-mPAavxcKIr-3oEtiKxVjI2c6aApvOjEKdDoyCnU6Ng8.01.170p7h020"
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
#    Path = "/home/gitlab-runner/cache_for_shell"d
