stages:
    - build
    # - deploy


variables:
  BUILD_DIR: build
  SERVER_USER_: $SERVER_USER_BETA
  SERVER_IP_: $SERVER_IP_BETA
  SERVER_PATH_: $SERVER_PATH_BETA
  SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY_BETA
  ENV_FILE_: $ENV_BETA_SEP

build:
    image: node:20
    stage: build
    only:
        - beta
    before_script:
        - echo "Switch to runflare repositories"
        - sed -i 's/deb.debian.org/linux-mirror.liara.ir\/repository/g' /etc/apt/sources.list.d/debian.sources
        - apt update -y && apt install -y openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY_" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "Host $SERVER_IP_" >> ~/.ssh/config
        - echo "    StrictHostKeyChecking no" >> ~/.ssh/config # Be cautious with this in production!
        - chmod 644 ~/.ssh/config
    script:
        - echo "Switch to Iran mirror for npm"
        # - npm config set registry https://mirror-npm.runflare.com
        - npm --silent i --force
        - echo "Set .env file to project"
        # - cp .env.example .env
        - cp $ENV_FILE_ ./.env
        - npm --silent run build
        - mkdir export
        - mv .env export/.
        - mv .next export/.
        - mv public export/.
        - mv node_modules export/.
        - echo "Sync data to server"
        - apt install -y rsync
        - rsync -az --delete ./export/* ${SERVER_USER_}@${SERVER_IP_}:${SERVER_PATH_}
        - rsync -az --delete ./export/.* ${SERVER_USER_}@${SERVER_IP_}:${SERVER_PATH_}
        - echo "Make node_modules back to cache folder"
        - mv export/node_modules .
        - |
            ssh -o StrictHostKeyChecking=no \
                -o IdentityFile=~/.ssh/id_edtemp \
                $SERVER_USER_@$SERVER_IP_ << EOF
                    pm2 restart SepehrinoLanding
            EOF
    # artifacts:
    #     paths:
    #         - export
    #     expire_in: 1 hour
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - node_modules/


# deploy-prod:
#     stage: deploy
#     image: ubuntu:20.04
#     dependencies:
#         - build
#     only:
#         - beta2
#     before_script:
#     #Switch to Iran mirrors
#         - sed -i 's/archive.ubuntu.com/mirror.arvancloud.ir/g' /etc/apt/sources.list
#         - apt-get update -qq && apt-get install -y -qq rsync openssh-client
#         - eval $(ssh-agent -s)
#         - echo "$SSH_PRIVATE_KEY_BETA"
#         - echo "$SSH_PRIVATE_KEY_BETA" | tr -d '\r' | ssh-add -
#         - mkdir -p ~/.ssh
#         - chmod 700 ~/.ssh
#         - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
#         - chmod 644 ~/.ssh/known_hosts
#     script:
#     - echo "Deploying to server"
#     - mkdir export
#     - echo hi > export/hi.txt
#     - rsync -avz --delete ./export/* ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}
#     # - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "cd /var/www/sepehrino-landing/ && git pull origin main"
#     # - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "cd /var/www/sepehrino-landing/ && yarn"
#     # - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "cd /var/www/sepehrino-landing/ && npm run build"
#     # - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "supervisorctl restart sepehrino-landing:*"
#     - echo "Deployed."
#     retry:
#         max: 1
#         # when: always


# build:
#     stage: build
#     image: node:16.14
#     script:
#         - yarn
#         - npm run build

# deploy-prod:
#     stage: deploy
#     image: ubuntu:20.04
#     dependencies:
#         - build
#     only:
#         - main
#     before_script:
#         - apt update -y
#         - apt-get install sshpass -y -qq
#         - sshpass -p "${PASSWORD}" ssh -i ~/.ssh/gitlab -v -o StrictHostKeyChecking=no ssh://${USERNAME}@${SERVER_IP}:2532
#     script:
#     - echo "Deploying to server"
#     - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "cd /var/www/sepehrino-landing/ && git pull origin main"
#     - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "cd /var/www/sepehrino-landing/ && yarn"
#     - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "cd /var/www/sepehrino-landing/ && npm run build"
#     - sshpass -p "${PASSWORD}" ssh ssh://${USERNAME}@${SERVER_IP}:2532 "supervisorctl restart sepehrino-landing:*"
#     - echo "Deployed."
#     retry:
#         max: 2
#         when: always
