stages:
  - build
  - deploy

variables:
  BUILD_DIR_: dist
  SERVER_USER_: $SERVER_USER
  SERVER_IP_: $SERVER_IP
  SERVER_PATH_: $SERVER_PATH
  SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY
  ENV_FILE_: $ENV_FILE
  SSH_PORT_: $SSH_PORT
  BRANCH: beta

build_react_app:
  image: node:20
  stage: build
  script:
    - echo "Switch to Iran mirror for npm"
    # - npm config set registry https://mirror-npm.runflare.com
    - echo "Installing project dependencies..."
    - if [ -f package-lock.json ]; then npm ci --legacy-peer-deps; else npm install --legacy-peer-deps; fi
    - echo "Building the React application..."
    - if [ -f "$ENV_FILE_" ]; then cp "$ENV_FILE_" .env; fi
    - CI=false npm run build
    - echo "Build artifacts are ready in the '${BUILD_DIR_}' directory."
  artifacts:
    paths:
      - ${BUILD_DIR_}
    expire_in: 1 hour
  cache:
    key:
      files:
        - package-lock.json
        - package.json
    paths:
      - node_modules/
  
  rules:
    - if: '$CI_COMMIT_BRANCH == $BRANCH || $BRANCH == ""'

deploy_app:
  stage: deploy
  before_script:
    #Switch to Iran mirrors
    - sed -i 's/archive.ubuntu.com/mirror.arvancloud.ir/g' /etc/apt/sources.list
    - apt-get update -qq && apt-get install -y -qq rsync openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $SSH_PORT_  $SERVER_IP_ >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying build artifacts to server..."
    - rsync -e "ssh -p $SSH_PORT_" -avz --delete ${BUILD_DIR_}/ ${SERVER_USER_}@${SERVER_IP_}:${SERVER_PATH_}
    - echo "Deployment complete!"
  # environment:
  #   name: production
  #   url: http://${SERVER_IP}
  when: on_success
  needs:
    - build_react_app
