FROM php:8.2.12-cli

# Set working directory
WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git curl zip unzip libonig-dev libxml2-dev libzip-dev \
    libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure zip \
    && docker-php-ext-install pdo pdo_mysql mbstring zip gd

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy app source
COPY . .

# Install Laravel PHP dependencies
RUN composer install --no-interaction --prefer-dist --optimize-autoloader


# Set permissions for Laravel
RUN chown -R www-data:www-data \
    /var/www/html/storage \
    /var/www/html/bootstrap/cache

# Expose port for artisan serve
EXPOSE 8000

RUN chmod +x ./start.sh

# Default command: run Laravel's built-in server
CMD ["./start-laravel.sh"]