version: '3.8'

services:
  nginx-migrator:
    image: python:3.11-slim
    container_name: nginx_to_npm_migrator
    network_mode: "host"
    volumes:
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - /etc/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./npm-migrate.py:/app/npm-migrate.py:ro
    working_dir: /app
    command: sh -c "pip install --no-cache-dir requests && python npm-migrate.py"

